website:
  title: "biosc1203_vml"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true



