project:
  type: website

website:
  title: "biosc1203_vml"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Geomorphometric Analysis

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

filters:
  - shinylive